-- Baseline Flyway (etape 2.21, ENF-30).
--
-- Reconstitue le schema tel que genere par ddl-auto=update jusqu'a la fin
-- du lot 2 (lots 0 a 2 inclus). Sur la base de developpement existante,
-- ce script n'est PAS execute : spring.flyway.baseline-on-migrate=true
-- se contente d'enregistrer un baseline a la version 1. Il sert de
-- reference pour toute base recreee de zero (nouvel environnement, CI).
--
-- Ordre des tables : utilisateur avant ses sous-types (heritage JOINED),
-- filiere/promotion avant etudiant, etudiant avant equipe (le chef d'equipe
-- est un etudiant), equipe avant l'ajout de la FK etudiant.equipe_id
-- (reference circulaire etudiant <-> equipe geree par un ALTER TABLE final),
-- et sujet/equipe avant projet.

-- ============================================================ utilisateur
CREATE TABLE utilisateur (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom                VARCHAR(60)  NOT NULL,
    prenom             VARCHAR(60)  NOT NULL,
    email              VARCHAR(120) NOT NULL,
    mot_de_passe       VARCHAR(72)  NOT NULL,
    telephone          VARCHAR(20),
    role               VARCHAR(20)  NOT NULL,
    actif              BOOLEAN      NOT NULL,
    date_creation      TIMESTAMP(6) NOT NULL,
    date_modification  TIMESTAMP(6),
    CONSTRAINT uk_utilisateur_email UNIQUE (email)
);

CREATE INDEX idx_utilisateur_role  ON utilisateur (role);
CREATE INDEX idx_utilisateur_actif ON utilisateur (actif);

-- ================================================================ filiere
CREATE TABLE filiere (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(10)  NOT NULL,
    libelle     VARCHAR(100) NOT NULL,
    departement VARCHAR(100),
    CONSTRAINT uk_filiere_code UNIQUE (code)
);

-- ============================================================== promotion
CREATE TABLE promotion (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    annee   INTEGER     NOT NULL,
    libelle VARCHAR(60) NOT NULL,
    CONSTRAINT uk_promotion_libelle UNIQUE (libelle)
);

-- =============================================================== etudiant
CREATE TABLE etudiant (
    id               BIGINT PRIMARY KEY REFERENCES utilisateur (id),
    numero_etudiant  VARCHAR(20) NOT NULL,
    date_naissance   DATE,
    filiere_id       BIGINT NOT NULL,
    promotion_id     BIGINT NOT NULL,
    equipe_id        BIGINT,
    CONSTRAINT uk_etudiant_numero UNIQUE (numero_etudiant),
    CONSTRAINT fk_etudiant_filiere   FOREIGN KEY (filiere_id)   REFERENCES filiere (id),
    CONSTRAINT fk_etudiant_promotion FOREIGN KEY (promotion_id) REFERENCES promotion (id)
);

-- ============================================================= superviseur
CREATE TABLE superviseur (
    id             BIGINT PRIMARY KEY REFERENCES utilisateur (id),
    specialite     VARCHAR(100),
    grade          VARCHAR(50),
    departement    VARCHAR(100),
    quota_projets  INTEGER NOT NULL
);

-- =========================================================== administrateur
CREATE TABLE administrateur (
    id            BIGINT PRIMARY KEY REFERENCES utilisateur (id),
    niveau_acces  VARCHAR(30)
);

-- ================================================================= equipe
-- Reference etudiant (chef_id) : etudiant existe deja a ce stade.
CREATE TABLE equipe (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom                VARCHAR(100) NOT NULL,
    taille_max         INTEGER      NOT NULL,
    chef_id            BIGINT       NOT NULL,
    date_creation      TIMESTAMP(6) NOT NULL,
    date_modification  TIMESTAMP(6),
    CONSTRAINT fk_equipe_chef FOREIGN KEY (chef_id) REFERENCES etudiant (id)
);

-- Reference circulaire etudiant <-> equipe : la FK est ajoutee une fois
-- les deux tables en place.
ALTER TABLE etudiant
    ADD CONSTRAINT fk_etudiant_equipe FOREIGN KEY (equipe_id) REFERENCES equipe (id);

-- =================================================================== sujet
CREATE TABLE sujet (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titre                    VARCHAR(150)  NOT NULL,
    description              VARCHAR(2000) NOT NULL,
    mots_cles                VARCHAR(200),
    capacite_max             INTEGER       NOT NULL,
    statut                   VARCHAR(20)   NOT NULL,
    encadrant_id             BIGINT        NOT NULL,
    filiere_id               BIGINT,
    commentaire_validation   VARCHAR(1000),
    date_proposition         TIMESTAMP(6)  NOT NULL,
    date_modification        TIMESTAMP(6),
    CONSTRAINT fk_sujet_encadrant FOREIGN KEY (encadrant_id) REFERENCES superviseur (id),
    CONSTRAINT fk_sujet_filiere   FOREIGN KEY (filiere_id)   REFERENCES filiere (id)
);

-- ================================================================== projet
CREATE TABLE projet (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sujet_id           BIGINT       NOT NULL,
    equipe_id          BIGINT       NOT NULL,
    encadrant_id       BIGINT       NOT NULL,
    statut             VARCHAR(20)  NOT NULL,
    date_affectation   TIMESTAMP(6) NOT NULL,
    date_modification  TIMESTAMP(6),
    CONSTRAINT uk_projet_sujet  UNIQUE (sujet_id),
    CONSTRAINT uk_projet_equipe UNIQUE (equipe_id),
    CONSTRAINT fk_projet_sujet     FOREIGN KEY (sujet_id)     REFERENCES sujet (id),
    CONSTRAINT fk_projet_equipe    FOREIGN KEY (equipe_id)    REFERENCES equipe (id),
    CONSTRAINT fk_projet_encadrant FOREIGN KEY (encadrant_id) REFERENCES superviseur (id)
);
