-- Lot 3, bloc A (jalons) : ajoute la table etape correspondant a l'entite
-- Etape introduite aux etapes 3.1 a 3.3. Developpee avec ddl-auto=update
-- (comme le lot 2), cette migration formalise le schema pour repasser
-- ddl-auto sur "validate" (etape 3.14).

-- =================================================================== etape
CREATE TABLE etape (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titre                    VARCHAR(150)  NOT NULL,
    description              VARCHAR(2000) NOT NULL,
    date_echeance            DATE          NOT NULL,
    ordre                    INTEGER       NOT NULL,
    statut                   VARCHAR(20)   NOT NULL,
    projet_id                BIGINT        NOT NULL,
    lien_livrable            VARCHAR(500),
    commentaire_soumission   VARCHAR(1000),
    date_soumission          TIMESTAMP(6),
    commentaire_validation   VARCHAR(1000),
    date_validation          TIMESTAMP(6),
    date_creation            TIMESTAMP(6)  NOT NULL,
    date_modification        TIMESTAMP(6),
    CONSTRAINT fk_etape_projet FOREIGN KEY (projet_id) REFERENCES projet (id)
);
