-- Lot 4, blocs A et B (documents versionnes, commentaires) : ajoute les
-- tables document et commentaire correspondant aux entites introduites aux
-- etapes 4.1 et 4.6. Developpee avec ddl-auto=update (comme les lots 2 et 3),
-- cette migration formalise le schema pour repasser ddl-auto sur "validate"
-- (etape 4.12).

-- ============================================================== document
CREATE TABLE document (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom                 VARCHAR(255) NOT NULL,
    type                VARCHAR(150) NOT NULL,
    taille              BIGINT       NOT NULL,
    chemin_minio        VARCHAR(500) NOT NULL,
    version             INTEGER      NOT NULL,
    projet_id           BIGINT       NOT NULL,
    etape_id            BIGINT,
    uploadeur_id        BIGINT       NOT NULL,
    date_upload         TIMESTAMP(6) NOT NULL,
    supprime            BOOLEAN      NOT NULL,
    date_suppression    TIMESTAMP(6),
    CONSTRAINT uk_document_chemin_minio UNIQUE (chemin_minio),
    CONSTRAINT fk_document_projet     FOREIGN KEY (projet_id)    REFERENCES projet (id),
    CONSTRAINT fk_document_etape      FOREIGN KEY (etape_id)     REFERENCES etape (id),
    CONSTRAINT fk_document_uploadeur  FOREIGN KEY (uploadeur_id) REFERENCES utilisateur (id)
);

CREATE INDEX idx_document_projet           ON document (projet_id);
CREATE INDEX idx_document_etape            ON document (etape_id);
CREATE INDEX idx_document_projet_nom_etape ON document (projet_id, nom, etape_id);

-- ============================================================ commentaire
CREATE TABLE commentaire (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contenu        VARCHAR(2000) NOT NULL,
    auteur_id      BIGINT        NOT NULL,
    document_id    BIGINT,
    etape_id       BIGINT,
    date_creation  TIMESTAMP(6)  NOT NULL,
    CONSTRAINT fk_commentaire_auteur   FOREIGN KEY (auteur_id)   REFERENCES utilisateur (id),
    CONSTRAINT fk_commentaire_document FOREIGN KEY (document_id) REFERENCES document (id),
    CONSTRAINT fk_commentaire_etape    FOREIGN KEY (etape_id)    REFERENCES etape (id)
);

CREATE INDEX idx_commentaire_document ON commentaire (document_id);
CREATE INDEX idx_commentaire_etape    ON commentaire (etape_id);
