-- Lot 5, blocs A et B (messagerie, bibliotheque de ressources) : ajoute les
-- tables message et ressource correspondant aux entites introduites aux
-- etapes 5.1 et 5.4. Developpee avec ddl-auto=update (comme les lots 2, 3
-- et 4), cette migration formalise le schema pour repasser ddl-auto sur
-- "validate" (etape 5.11).

-- ================================================================= message
CREATE TABLE message (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contenu      VARCHAR(2000) NOT NULL,
    auteur_id    BIGINT        NOT NULL,
    projet_id    BIGINT        NOT NULL,
    date_envoi   TIMESTAMP(6)  NOT NULL,
    CONSTRAINT fk_message_auteur FOREIGN KEY (auteur_id) REFERENCES utilisateur (id),
    CONSTRAINT fk_message_projet FOREIGN KEY (projet_id) REFERENCES projet (id)
);

CREATE INDEX idx_message_projet ON message (projet_id);

-- =============================================================== ressource
CREATE TABLE ressource (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titre                  VARCHAR(255)  NOT NULL,
    description            VARCHAR(2000),
    categorie              VARCHAR(100)  NOT NULL,
    lien                   VARCHAR(500),
    fichier_nom            VARCHAR(255),
    fichier_type           VARCHAR(150),
    fichier_taille         BIGINT,
    fichier_chemin_minio   VARCHAR(500),
    auteur_id              BIGINT        NOT NULL,
    date_creation          TIMESTAMP(6)  NOT NULL,
    CONSTRAINT fk_ressource_auteur FOREIGN KEY (auteur_id) REFERENCES utilisateur (id)
);

CREATE INDEX idx_ressource_categorie ON ressource (categorie);
