-- Detection de similarite entre rapports deposes et rapports archives.
--
-- Formalise le schema developpe avec ddl-auto=update, pour repasser sur
-- "validate" comme aux lots precedents. Cinq objets :
--   1. colonnes d'archivage ajoutees a la table document existante
--   2. indexation_document : texte extrait des PDF
--   3. morceau_document    : fragments et vecteurs pgvector
--   4. rapport_similarite  : resultat date d'une analyse
--   5. correspondance_similarite : rapprochements retenus
--
-- L'extension pgvector est deja activee par le callback beforeMigrate.sql,
-- execute avant toute migration. Elle est redeclaree ici pour que ce fichier
-- reste autonome : appliquer les migrations sans le callback doit fonctionner.
CREATE EXTENSION IF NOT EXISTS vector;

-- ========================================================= archivage document
-- Marque un document comme rapport de reference. Seuls les documents portant
-- ce marqueur forment le corpus de comparaison : les rapports simplement
-- deposes sur un projet n'y entrent pas.
--
-- DEFAULT FALSE est indispensable ici, contrairement au mapping JPA : la
-- table contient deja des lignes, et une colonne NOT NULL sans valeur par
-- defaut serait refusee par PostgreSQL.
ALTER TABLE document
    ADD COLUMN archive         BOOLEAN      NOT NULL DEFAULT FALSE,
    ADD COLUMN date_archivage  TIMESTAMP(6),
    ADD COLUMN archive_par_id  BIGINT;

ALTER TABLE document
    ADD CONSTRAINT fk_document_archive_par
        FOREIGN KEY (archive_par_id) REFERENCES utilisateur (id);

CREATE INDEX idx_document_archive ON document (archive);

-- ==================================================== indexation_document
-- Table separee de document, et non colonnes supplementaires : le texte d'un
-- rapport pese facilement plusieurs centaines de kilo-octets, et JPA charge
-- les colonnes basiques en eager. Les stocker sur document ferait rapatrier
-- l'integralite des rapports a chaque liste de documents.
--
-- La contrainte CHECK sur statut est declaree explicitement avec les six
-- valeurs de l'enum. Motif : Hibernate genere cette contrainte au moment ou
-- il CREE la table, en y figeant les valeurs connues alors, et ddl-auto=update
-- ne la met jamais a jour ensuite. C'est ce qui a fait echouer l'insertion de
-- VECTORISE en developpement, la table ayant ete creee avant l'ajout de cette
-- valeur. La declarer ici garantit qu'une base recreee de zero soit d'emblee
-- coherente avec l'enum Java.
CREATE TABLE indexation_document (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id      BIGINT       NOT NULL,
    texte            TEXT,
    statut           VARCHAR(30)  NOT NULL,
    nb_caracteres    INTEGER      NOT NULL,
    nb_pages         INTEGER,
    tronque          BOOLEAN      NOT NULL,
    nb_morceaux      INTEGER      NOT NULL,
    message          VARCHAR(500),
    date_extraction  TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_indexation_document UNIQUE (document_id),
    CONSTRAINT fk_indexation_document FOREIGN KEY (document_id) REFERENCES document (id),
    CONSTRAINT indexation_document_statut_check
        CHECK (statut IN ('EXTRAIT', 'VECTORISE', 'ECHEC_EMBEDDING',
                          'VIDE', 'TYPE_NON_SUPPORTE', 'ECHEC'))
);

CREATE INDEX idx_indexation_statut ON indexation_document (statut);

-- ======================================================== morceau_document
-- Un vecteur par fragment de texte, et non un par document. Deux raisons :
-- le modele d'embeddings plafonne a 8192 tokens par appel, et surtout un
-- vecteur unique moyenne sur cent pages ne rapproche que des rapports de meme
-- theme, alors que le plagiat reel porte sur un chapitre.
--
-- La dimension 768 est figee ici, dans MorceauDocument.DIMENSION et dans
-- gemini.embeddings.dimension. En changer impose de reindexer tout le corpus :
-- des vecteurs de dimensions differentes ne sont pas comparables.
CREATE TABLE morceau_document (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    indexation_id  BIGINT      NOT NULL,
    ordre          INTEGER     NOT NULL,
    texte          TEXT        NOT NULL,
    vecteur        vector(768),
    CONSTRAINT uk_morceau_indexation_ordre UNIQUE (indexation_id, ordre),
    CONSTRAINT fk_morceau_indexation
        FOREIGN KEY (indexation_id) REFERENCES indexation_document (id)
);

CREATE INDEX idx_morceau_indexation ON morceau_document (indexation_id);

-- ====================================================== rapport_similarite
-- Un rapport est un cliche date : il conserve les seuils en vigueur au moment
-- de l'analyse et la taille du corpus compare. Sans cela, un rapport relu six
-- mois plus tard serait ininterpretable - on ne saurait pas si un document non
-- signale l'a ete parce qu'il etait original, ou parce que le corpus etait
-- alors vide.
--
-- Plusieurs rapports coexistent pour un meme document : relancer une analyse
-- apres enrichissement du corpus ajoute une ligne au lieu d'ecraser la
-- precedente, ce qui preserve l'historique des verifications.
CREATE TABLE rapport_similarite (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id            BIGINT           NOT NULL,
    demande_par_id         BIGINT,
    score_max              DOUBLE PRECISION NOT NULL,
    niveau                 VARCHAR(20)      NOT NULL,
    nb_documents_compares  INTEGER          NOT NULL,
    nb_morceaux_analyses   INTEGER          NOT NULL,
    seuil_suspect          DOUBLE PRECISION NOT NULL,
    seuil_attention        DOUBLE PRECISION NOT NULL,
    date_analyse           TIMESTAMP(6)     NOT NULL,
    CONSTRAINT fk_rapport_similarite_document
        FOREIGN KEY (document_id) REFERENCES document (id),
    CONSTRAINT fk_rapport_similarite_demandeur
        FOREIGN KEY (demande_par_id) REFERENCES utilisateur (id),
    CONSTRAINT rapport_similarite_niveau_check
        CHECK (niveau IN ('AUCUN', 'ATTENTION', 'SUSPECT'))
);

CREATE INDEX idx_rapport_similarite_document ON rapport_similarite (document_id);
CREATE INDEX idx_rapport_similarite_niveau   ON rapport_similarite (niveau);

-- ================================================ correspondance_similarite
-- Une ligne par document archive rapproche, avec la meilleure correspondance
-- trouvee. Les deux extraits sont stockes en dur plutot que reconstruits a la
-- demande : le rapport doit rester verifiable meme si l'archive est ensuite
-- demarquee, reindexee avec un decoupage different ou supprimee. D'ou aussi
-- document_archive_nom, conserve independamment de la cle etrangere.
CREATE TABLE correspondance_similarite (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rapport_id             BIGINT           NOT NULL,
    document_archive_id    BIGINT,
    document_archive_nom   VARCHAR(255),
    score                  DOUBLE PRECISION NOT NULL,
    ordre_morceau_analyse  INTEGER          NOT NULL,
    ordre_morceau_archive  INTEGER          NOT NULL,
    extrait_analyse        TEXT,
    extrait_archive        TEXT,
    CONSTRAINT fk_correspondance_rapport
        FOREIGN KEY (rapport_id) REFERENCES rapport_similarite (id),
    CONSTRAINT fk_correspondance_archive
        FOREIGN KEY (document_archive_id) REFERENCES document (id)
);

CREATE INDEX idx_correspondance_rapport ON correspondance_similarite (rapport_id);
CREATE INDEX idx_correspondance_archive ON correspondance_similarite (document_archive_id);
