-- Notifications in-app (Lot 7, bloc A) et journal d'audit (Lot 7, bloc B).
--
-- Formalise le schema developpe avec ddl-auto=update le temps du Lot 7, pour
-- repasser sur "validate" comme aux lots precedents (etape 7.15). Deux tables
-- independantes, sans lien entre elles :
--   1. notification  : notifications in-app adressees a un utilisateur (7.1)
--   2. entree_audit  : journal d'audit ecrit via @Audite / AuditAspect (7.6)
--
-- La contrainte CHECK sur notification.type est declaree explicitement avec
-- les sept valeurs de TypeNotification, meme lecon qu'au lot 6 (V5, statut
-- d'indexation) : Hibernate fige les valeurs connues au moment ou il CREE la
-- table sous ddl-auto=update, et ne met jamais cette contrainte a jour
-- ensuite. La declarer ici garantit qu'une base recreee de zero soit
-- d'emblee coherente avec l'enum Java, meme si celui-ci s'enrichit plus tard.
--
-- entree_audit.action n'a pas cette contrainte : ce n'est pas un enum mais un
-- code libre porte par chaque annotation @Audite (etape 7.8), avec sa propre
-- convention "{action}_ECHEC" sur echec - une liste fermee n'aurait pas de sens.

-- ============================================================= notification
CREATE TABLE notification (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    destinataire_id  BIGINT       NOT NULL,
    type             VARCHAR(30)  NOT NULL,
    message          VARCHAR(500) NOT NULL,
    lien             VARCHAR(255),
    lue              BOOLEAN      NOT NULL,
    date_creation    TIMESTAMP(6) NOT NULL,
    date_lecture     TIMESTAMP(6),
    CONSTRAINT fk_notification_destinataire
        FOREIGN KEY (destinataire_id) REFERENCES utilisateur (id),
    CONSTRAINT notification_type_check
        CHECK (type IN ('SUJET_VALIDE', 'SUJET_REJETE', 'JALON_SOUMIS', 'JALON_VALIDE',
                         'DOCUMENT_DEPOSE', 'NOUVEAU_MESSAGE', 'SIMILARITE_SUSPECT'))
);

-- Seul destinataire_id est filtre en base (NotificationRepository) : lue et
-- date_creation n'interviennent qu'en tri/projection sur le resultat deja
-- restreint au destinataire.
CREATE INDEX idx_notification_destinataire ON notification (destinataire_id);

-- ============================================================= entree_audit
-- Append-only : pas de date de modification, pas de suppression logique - un
-- journal d'audit qui peut etre corrige perd sa valeur probante (EntreeAudit).
CREATE TABLE entree_audit (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    acteur      VARCHAR(120)  NOT NULL,
    action      VARCHAR(50)   NOT NULL,
    cible       VARCHAR(255),
    detail      VARCHAR(1000),
    horodatage  TIMESTAMP(6)  NOT NULL,
    ip          VARCHAR(45)
);

-- Les trois colonnes filtrables d'AuditController (etape 7.9) : acteur
-- (recherche partielle), action (exact), horodatage (plage de dates).
CREATE INDEX idx_entree_audit_acteur     ON entree_audit (acteur);
CREATE INDEX idx_entree_audit_action     ON entree_audit (action);
CREATE INDEX idx_entree_audit_horodatage ON entree_audit (horodatage);
