-- Assistant conversationnel RAG (Lot 8, EF-48, cahier des charges section 3.1
-- / chapitre 7, diagramme de sequence 6).
--
-- Formalise le schema developpe avec ddl-auto=update le temps du Lot 8, pour
-- repasser sur "validate" a la cloture (etape 8.14), meme convention qu'aux
-- lots precedents (2.21, 3.14, 4.12, 5.11, 6.10, 7.15).
--
-- Deux changements independants, tous deux crees localement sous
-- ddl-auto=update pendant ce lot :
--   1. article_aide : nouvelle table, corpus FAQ de l'assistant (etape 8.4).
--   2. equipe.code_invitation : colonne ajoutee hors-plan en cours de lot,
--      pour le passage de l'auto-inscription par liste ouverte a la
--      inscription par code (cf. Javadoc de Equipe.java).
--
-- Meme lecon qu'aux lots 6 et 7 (V5, V6) pour statut_indexation : Hibernate
-- fige la contrainte CHECK au moment ou il CREE la table sous ddl-auto=update
-- et ne la met jamais a jour ensuite ; elle est donc declaree ici
-- explicitement avec les trois valeurs de StatutIndexationArticle, pour
-- qu'une base recreee de zero reste coherente avec l'enum Java.
--
-- L'extension pgvector est deja activee par le callback beforeMigrate.sql
-- (etape 6.3) : aucune commande manuelle requise ici.

-- ========================================================== article_aide
CREATE TABLE article_aide (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titre              VARCHAR(255)  NOT NULL,
    contenu            TEXT          NOT NULL,
    categorie          VARCHAR(100)  NOT NULL,
    statut_indexation  VARCHAR(30)   NOT NULL,
    vecteur            vector(768),
    date_creation      TIMESTAMP(6)  NOT NULL,
    date_maj           TIMESTAMP(6)  NOT NULL,
    CONSTRAINT article_aide_statut_indexation_check
        CHECK (statut_indexation IN ('EN_ATTENTE', 'VECTORISE', 'ECHEC'))
);

-- Pas d'index pgvector (ivfflat/hnsw) : corpus d'une vingtaine d'articles au
-- plus, un scan complet avec l'operateur de distance cosinus (<=>) suffit,
-- meme choix qu'au lot 6 pour morceau_document.
CREATE INDEX idx_article_aide_categorie          ON article_aide (categorie);
CREATE INDEX idx_article_aide_statut_indexation  ON article_aide (statut_indexation);

-- ================================================================= equipe
-- code_invitation reste NULLABLE ici : sous ddl-auto=update, une colonne
-- NOT NULL ajoutee par ALTER TABLE sur une table non vide (l'equipe de test
-- creee avant ce changement) echoue faute de DEFAULT. Meme choix que dans
-- Equipe.java (@Column sans nullable = false) : l'unicite et la non-nullite
-- reelle sont garanties par EquipeService (generation a la creation,
-- retro-generation au premier chargement pour une equipe plus ancienne). Une
-- contrainte UNIQUE autorise plusieurs NULL simultanes en Postgres, ce qui
-- convient tant qu'une equipe preexistante n'a pas encore ete relue.
ALTER TABLE equipe ADD COLUMN code_invitation VARCHAR(8);
ALTER TABLE equipe ADD CONSTRAINT uk_equipe_code_invitation UNIQUE (code_invitation);
